### ISSUE TITLE
pip version doesn't know where the databases are

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/ngmaster#15]
```
% ngmaster ~/tmp/San_2016-00058.fasta
Traceback (most recent call last):
  File "/home/tseemann/.local/bin/ngmaster", line 9, in <module>
    load_entry_point('ngmaster==0.3', 'console_scripts', 'ngmaster')()
  File "/home/tseemann/.local/lib/python2.7/site-packages/ngmaster/ngmaster.py", line 167, in main
    with open(alleleDB) as f:
IOError: [Errno 2] No such file or directory: '/home/tseemann/.local/lib/python2.7/site-packages/ngmaster/db/ng_mast.txt'
```

**Comment by andersgs** [comment]
Should work now:

     pip install --upgrade --user git+https://github.com/MDU-PHL/ngmaster.git

No need to clone the repo.

We can also make it more specific in the future:

    pip install --user git+https://mygithub/myrepo.git[@tag][#egg=Dependency]

**Comment by andersgs** [comment]
This was an install issue. It is fixed now.
